## Customize the test machine
machine:

  timezone:
    Europe/Dublin
    #America/Los_Angeles # Set the timezone

  # Version of ruby to use
  ruby:
    version:
      2.4.0

  # Add some environment variables
  environment:
    CIRCLE_ENV: test
    DATABASE_URL: postgresql://ubuntu:@127.0.0.1:5432/circle_test

## Customize checkout
checkout:
  post:
    - git submodule sync
    #- git submodule update --init # use submodule

  override:
    - bundle install: # note ':' here
        timeout: 180 # fail if command has no output for 3 minutes
        # IMPORTANT NOTE: ^^ the timeout modifier above must be
        # double indented (four spaces) from the previous line
  
  # we automatically cache and restore many dependencies between
  # builds. If you need to, you can add custom paths to cache:
  cache_directories:
    - "custom_1"   # relative to the build directory
    - "~/custom_2" # relative to the user's home directory

compile:
  override:
    - jeykll build

## Customize test commands
test:
  post:
    echo "All good"
    
## Customize deployment commands
deployment:
  production:
    branch: master
    commands:
      - aws s3 sync ./_site/ s3://ds.limited/ --delete